<?php

namespace App\Providers;

use App\Events\ComposerActionLoggedToConsole;
use App\Listeners\SynologyExtendSocialiteListener;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use SocialiteProviders\Manager\SocialiteWasCalled;

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        SocialiteWasCalled::class => [
            \SocialiteProviders\Discord\DiscordExtendSocialite::class . '@handle', // code: this is an autogenerated line
            SynologyExtendSocialiteListener::class.'@handle', // code: this is an autogenerated line
        ],
        ComposerActionLoggedToConsole::class => [
        ],
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Determine if events and listeners should be automatically discovered.
     *
     * @return bool
     */
    public function shouldDiscoverEvents()
    {
        return false;
    }
}
