name: Build Base Image

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  tests:
    environment: Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Print username
        run: |
          echo "${{ secrets.DOCKERHUB_USERNAME }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker/base
          push: true
          tags: austinkregel/base:${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker/base
          push: true
          tags: austinkregel/base:latest
