name: Build and Publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_SECRET_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "sha7=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/austinkregel/aut.hair:latest
            ghcr.io/austinkregel/aut.hair:${{ steps.vars.outputs.sha7 }}
