name: Production build

on: [workflow_call]

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, redis, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install NPM
        run: |
          curl https://lazy.build/nodejs@ubuntu:18 | sudo bash
          sudo npm install --global yarn
          yarn
          yarn run build

      - name: Install AWS CLI
        run: sudo apt-get update && sudo apt-get install awscli -y

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DO_SPACE_ENDPOINT: ${{ secrets.DO_SPACE_ENDPOINT }} # Ensure you have this secret set in your GitHub repository
          DO_SPACE_REGION: ${{ secrets.DO_SPACE_REGION }} # Ensure you have this secret set in your GitHub repository
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $DO_SPACE_REGION
          aws configure set default.output json
          aws configure set default.s3.endpoint $DO_SPACE_ENDPOINT

      - name: Copy assets to Digital Ocean Space
        env:
          DO_SPACE_BUCKET_NAME: ${{ secrets.DO_SPACE_BUCKET_NAME }}
          DO_SPACE_REGION: ${{ secrets.DO_SPACE_REGION }}
          DO_SPACE_ENDPOINT: ${{ secrets.DO_SPACE_ENDPOINT }}
        run: |
          zip -r production.zip public/build
          aws s3 cp production.zip s3://$DO_SPACE_BUCKET_NAME/production.zip --endpoint-url $DO_SPACE_ENDPOINT --recursive
